baseURL = 'https://shivanibhardwaj.com/blog/'
languageCode = 'en-us'
title = "Shivani's very boring blog"
paginate = 5
theme = "papermod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Shivani's very boring blog"
description = "A journal of new learnings that can possibly help you"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Shivani"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

#[params.assets]
#favicon = "<link / abs url>"
#favicon16x16 = "<link / abs url>"
#favicon32x32 = "<link / abs url>"
#apple_touch_icon = "<link / abs url>"
#safari_pinned_tab = "<link / abs url>"

[params.label]
text = "Home"
icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = false
title = "ExampleSite"
subtitle = "This is subtitle"
imageUrl = "<img location>"
imageWidth = 120
imageHeight = 120
imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[params.homeInfoParams]
Title = "Helleoooo, beautiful human! 👋"
Content = "Welcome to my blog"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/3715736/unixia"

[[params.socialIcons]]
name = "github"
url = "https://github.com/inashivb"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/tuxish"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.editPost]
URL = "https://github.com/inashivb/blog/content"
Text = "Suggest Changes"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

#[[menu.main]]
#identifier = "example"
#name = "example.org"
#url = "https://example.org"
#weight = 30

[markup.highlight]
noClasses = false

